packages/ui/__stories__/Button.stories.tsx
packages/ui/__tests__/Button.test.tsx
packages/ui/src/Button.tsx

feat: add button disabled tooltip

---

packages/ui/__tests__/NumberField.test.tsx
packages/ui/src/NumberField.tsx

Closes the bug reported at https://github.com/hazelcast/frontend-shared/pull/76#discussion_r527585859

Fix empty string handling for the `NumberField`

---

packages/ui/src/Alert.tsx
packages/ui/src/IconButton.module.scss
packages/ui/src/Label.module.scss
packages/ui/src/TextArea.module.scss
packages/ui/src/TextField.module.scss

Remove top-level margin

---

packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/NumberField.tsx
packages/ui/src/TextArea.tsx
packages/ui/src/TruncatedText.tsx

useIsomorphicLayoutEffect is still required in NumberField because onChange synchronously queues a state update in parent component and violates encapsulation and React warns - https://fb.me/setstate-in-render

Use useIsomorphicLayoutEffect

---

packages/ui/src/SelectField.tsx
packages/ui/src/utils/ssr.ts

Fix SelectField rendering in SSR env

---

packages/ui/__tests__/Link.test.tsx
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/Alert.tsx
packages/ui/src/Link.tsx

Extend Link API to support NextJS integration

---

README.md
packages/ui/__stories__/Radio.stories.tsx
packages/ui/__stories__/RadioGroup.stories.tsx
packages/ui/__tests__/Checkbox.test.tsx
packages/ui/__tests__/Radio.test.tsx
packages/ui/__tests__/SelectField.test.tsx
packages/ui/__tests__/TextArea.test.tsx
packages/ui/__tests__/TextField.test.tsx
packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/Button.tsx
packages/ui/src/Checkbox.tsx
packages/ui/src/Radio.tsx
packages/ui/src/RadioGroup.tsx
packages/ui/src/SelectField.tsx
packages/ui/src/TextArea.tsx
packages/ui/src/TextField.tsx
packages/ui/src/TruncatedText.tsx

Add uuid support to SSR

---

packages/ui/__stories__/Checkbox.stories.tsx
packages/ui/__stories__/Radio.stories.tsx
packages/ui/__stories__/RadioGroup.stories.tsx
packages/ui/__stories__/decorators.tsx

Wrap all radio stories in form

---

packages/ui/src/Badge.tsx
packages/ui/src/Toast.tsx

We were missing the possibility to add `className` for these two.

Adds className property for Toast and Badge

---

packages/ui/__tests__/TextField.test.tsx
packages/ui/src/TextField.tsx

Support for onKeyPress for TextField

---

packages/ui/styles/constants/_typography.scss

- Adds typographyBodySmall
- Adds typographyBodyTiny
- Both are used in our new SidebarMenu

feat: add bodySmaller and bodyTiny font sizes

---

packages/ui/src/AutocompleteField.tsx

update(ui): handle clicked state of the autocomplete

---

packages/ui/package.json
packages/ui/src/Slider.tsx

update(ui): use helper function

---

packages/ui/src/Calendar/Calendar.module.scss
packages/ui/src/Calendar/Calendar.tsx

fix(styles): use class name for all css rules

---

packages/ui/__tests__/Select/CheckableSelectField.test.tsx
packages/ui/__tests__/TextField.test.tsx
packages/ui/src/Error.tsx
packages/ui/src/TextField.tsx
packages/ui/src/Tooltip.tsx
packages/ui/src/TruncatedText.tsx

fix* TextField error tooltip hides on hover

feat* TextField error tooltip placement can be adjusted

---

packages/ui/src/Code.tsx
packages/ui/src/CodeEditor.tsx
packages/ui/src/Table/Table.tsx

feat* Add autoResetExpanded property to Table

feat* Add dataTest property to CodeEditor

---

packages/ui/src/CodeEditorFormik.tsx

feat* onChange and onBlur callbacks can be passed to CodeEditorFormik

fix* Trigger CodeEditorFormik validation on change

---

packages/ui/src/Calendar/Calendar.tsx
packages/ui/src/Calendar/CalendarRange.tsx
packages/ui/src/Calendar/components/CalendarTime.tsx
packages/ui/src/Select/CheckableSelectField.module.scss

feat* CustomTimeField - custom time input
fix* Calendar popperContainer remounting
fix* Increase CheckableSelectField z-index to appear over Modal

feat* Calendar 24-hour time format

---

packages/ui/src/Table/CellWrapper.tsx
packages/ui/src/Table/Table.tsx
packages/ui/src/Table/TableContent.module.scss
packages/ui/src/Table/TableContent.tsx
packages/ui/src/Table/features/columnsSelection/columnsSelection.ts

*fix Ignore hotkeys on Table sub rows

*fix Clear unselected table cell values

---

packages/ui/src/FieldHeader.tsx
packages/ui/src/Help.tsx
packages/ui/src/TextField.tsx
packages/ui/src/Tooltip.tsx

*feat Adjustable TextField helper text tooltip word-break

*feat Adjustable Tooltip word-break

---

packages/ui/__tests__/AutocompleteField.test.tsx
packages/ui/__tests__/Calendar/components/CalendarTime.test.tsx
packages/ui/__tests__/NumberField.test.tsx
packages/ui/__tests__/Pagination.test.tsx
packages/ui/__tests__/SegmentedControl.test.tsx
packages/ui/__tests__/Select/CheckableSelectField.test.tsx
packages/ui/__tests__/Toggle.test.tsx
packages/ui/src/AutocompleteField.tsx
packages/ui/src/FieldHeader.tsx
packages/ui/src/Icon.tsx
packages/ui/src/NumberField.tsx
packages/ui/src/SegmentedControl.tsx
packages/ui/src/TextField.tsx
packages/ui/src/Toggle.tsx

[HZC-4932](https://hazelcast.atlassian.net/browse/HZC-4932)
[HZC-4932]: https://hazelcast.atlassian.net/browse/HZC-4932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HZC-4932: Make label optional for some HIVE components

---

packages/ui/src/Button.tsx

Missed one type usage in previous PR

HZC-5335 button typing enhancement

---

packages/ui/package.json
packages/ui/src/ContextMenu.tsx
packages/ui/src/Popover.tsx
packages/ui/src/Table/Table.tsx
packages/ui/src/Table/TableContent.tsx
packages/ui/src/TextField.tsx
packages/ui/src/hooks/useOnClickOutside.ts
pnpm-lock.yaml

*fix remove focus trap from popover
*fix Table context menu appearance on header cells

Remove focus trap from Popover and disable Table context menu on header cells

---

packages/ui/__stories__/Tooltip.stories.tsx
packages/ui/src/Tooltip.tsx

https://hazelcast.atlassian.net/browse/HZC-6966

HZC-6966: enforce-tooltip-visibility

---

.github/actions/install/action.yml

fixes the error https://github.com/hazelcast/hive/actions/runs/14082624838/job/39438958874

Fix error on canary release
